package com.newframework.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CONNECT".
*/
public class ConnectDao extends AbstractDao<Connect, String> {

    public static final String TABLENAME = "CONNECT";

    /**
     * Properties of entity Connect.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property UserId = new Property(0, String.class, "userId", true, "USER_ID");
    }


    public ConnectDao(DaoConfig config) {
        super(config);
    }
    
    public ConnectDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CONNECT\" (" + //
                "\"USER_ID\" TEXT PRIMARY KEY NOT NULL UNIQUE );"); // 0: userId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CONNECT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Connect entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getUserId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Connect entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getUserId());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    @Override
    public Connect readEntity(Cursor cursor, int offset) {
        Connect entity = new Connect( //
            cursor.getString(offset + 0) // userId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Connect entity, int offset) {
        entity.setUserId(cursor.getString(offset + 0));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Connect entity, long rowId) {
        return entity.getUserId();
    }
    
    @Override
    public String getKey(Connect entity) {
        if(entity != null) {
            return entity.getUserId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Connect entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
