package com.newframework.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;
import org.greenrobot.greendao.annotation.Unique;

/**
 * Entity mapped to table "connect".
 */
@Entity
public class Connect {

    @Id
    @Unique
    @NotNull
    private String userId;

    @Generated(hash = 588077612)
    public Connect(@NotNull String userId) {
        this.userId = userId;
    }

    @Generated(hash = 1303120704)
    public Connect() {
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }
}
