package com.newframework.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Property;
import org.greenrobot.greendao.annotation.Unique;

import java.io.Serializable;

@Entity
public class Groups implements Serializable {
    public static final long serialVersionUID = 547820201;
    @Id
    @Unique
    private String groupId;
    @Property
    private String name;
    @Property
    private String image;
    @Property
    private String desc;
    @Property
    private String count;
    @Property
    private String flag;
    @Property
    private String docId;

    @Generated(hash = 554281112)
    public Groups(String groupId, String name, String image, String desc, String count, String flag,
                  String docId) {
        this.groupId = groupId;
        this.name = name;
        this.image = image;
        this.desc = desc;
        this.count = count;
        this.flag = flag;
        this.docId = docId;
    }

    @Generated(hash = 893039872)
    public Groups() {
    }

    public String getGroupId() {
        return this.groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getDesc() {
        return this.desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getFlag() {
        return this.flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

    public String getDocId() {
        return this.docId;
    }

    public void setDocId(String docId) {
        this.docId = docId;
    }

    public String getCount() {
        return this.count;
    }

    public void setCount(String count) {
        this.count = count;
    }
}
