package com.newframework.db;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;
import org.greenrobot.greendao.annotation.Property;
import org.greenrobot.greendao.annotation.Unique;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
@Entity
public class GroupMember {

    @Id
    @Unique
    private String groupId;
    @Property
    @NotNull
    private String userId;
    @Property
    private String name;
    @Property
    private String image;
    @Property
    private String title;
    @Property
    private String role;
    @Generated(hash = 66207487)
    public GroupMember(String groupId, @NotNull String userId, String name, String image, String title,
                       String role) {
        this.groupId = groupId;
        this.userId = userId;
        this.name = name;
        this.image = image;
        this.title = title;
        this.role = role;
    }
    @Generated(hash = 1668463032)
    public GroupMember() {
    }
    public String getGroupId() {
        return this.groupId;
    }
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }
    public String getUserId() {
        return this.userId;
    }
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getImage() {
        return this.image;
    }
    public void setImage(String image) {
        this.image = image;
    }
    public String getTitle() {
        return this.title;
    }
    public void setTitle(String title) {
        this.title = title;
    }
    public String getRole() {
        return this.role;
    }
    public void setRole(String role) {
        this.role = role;
    }

}
