package com.newframework.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PAT_TAGS".
*/
public class PatTagsDao extends AbstractDao<PatTags, String> {

    public static final String TABLENAME = "PAT_TAGS";

    /**
     * Properties of entity PatTags.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property TagName = new Property(1, String.class, "tagName", false, "TAG_NAME");
        public final static Property Userid = new Property(2, String.class, "userid", false, "USERID");
    }


    public PatTagsDao(DaoConfig config) {
        super(config);
    }
    
    public PatTagsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PAT_TAGS\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL UNIQUE ," + // 0: id
                "\"TAG_NAME\" TEXT," + // 1: tagName
                "\"USERID\" TEXT);"); // 2: userid
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PAT_TAGS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PatTags entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String tagName = entity.getTagName();
        if (tagName != null) {
            stmt.bindString(2, tagName);
        }
 
        String userid = entity.getUserid();
        if (userid != null) {
            stmt.bindString(3, userid);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PatTags entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String tagName = entity.getTagName();
        if (tagName != null) {
            stmt.bindString(2, tagName);
        }
 
        String userid = entity.getUserid();
        if (userid != null) {
            stmt.bindString(3, userid);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public PatTags readEntity(Cursor cursor, int offset) {
        PatTags entity = new PatTags( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // tagName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // userid
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PatTags entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTagName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUserid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final String updateKeyAfterInsert(PatTags entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(PatTags entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PatTags entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
